language: node_js

node_js:
  - "node"
  - "6"

after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_success: change
    on_failure: always
